### PR TITLE
add README-ko.md

### PR DESCRIPTION
**Pull request by pengooseDev**
# Feature
### '23.12.29
- [x] add README-ko.md
- [x] update README.md(add README-ko.md link)
- [x] update README-ja.md(add README-ko.md link) 

### '24.01.01
- [x] sync upstream docs update(resolve conflict & updatem README-ko.md)

---

EN : If you need a multilingual translation module for your application, please comment further :)
JA : アプリケーションに多言語翻訳モジュールが必要な場合は、追加的にコメントを残していただければ幸いです :)

### CODE REVIEW

**Comment by pengooseDev** [comment]
@cumulo-autumn
Add commit that Sync changes in upstream docs :)
I'd appreciate it if u leave a single comment with this PR's feedback

**Comment by cumulo-autumn** [comment]
Hi @pengooseDev. I am sorry for the late reply. We truly appreciate your great contribution to making the README-ko. It really helps. Currently, we are also preparing a Chinese version readme, README-zh. After that, we will merge your PR and put both links to the front page!

**Review by cumulo-autumn — APPROVED** [review]
Looks very good! Thank you for the adjustments to the README format and for adding the Korean README!

**Comment by cumulo-autumn** [comment]
@pengooseDev 
It seems that preparing the Chinese README is going to take a bit more time, so I went ahead and merged the Korean README you provided first! Thank you for your contribution!

**Pull request merged**
